### ISSUE TITLE
Support for multiple phasing structures for a single signal

### ISSUE THREAD

**Issue by pedrocamargo** [zephyr-data-specs/GMNS#57]
There are cases where phasing of intersection control changes during the day, and it would be good to have GMNS support that. Polaris supports this feature during simulation, and I guess other software would as well.

**Comment by ssmith55** [comment]
I'll consider what can be done, and will put proposed changes in the development branch.  Thank you for the feedback.

**Comment by ssmith55** [comment]
In the Development branch, I changed signal_phase_mvmt, so that it is associated to a record in the signal_timing_phase table (via timing_phase_id).  This allows both movements and timings to vary by time of day.  It means the signal_phase_mvmt table is now a bit larger.   The Arlington_Signals and Cambridge_v090 examples have also been updated.
